app:
  port: 8080
  jwtSecret: "interviewGenius_secret_key"

server:
  runMode: "debug"
  readTimeout: 60
  writeTimeout: 60

database:
  type: "mysql"
  user: "root"
  password: "wszxy123"
  host: "127.0.0.1"
  port: 3306
  name: "interview_genius"
  tablePrefix: ""

alipay:
  app_id: "您的支付宝应用ID"
  private_key: "您的应用私钥"
  is_prod: false  # 是否生产环境
  app_public_cert: "应用公钥证书内容"
  alipay_root_cert: "支付宝根证书内容"
  alipay_public_cert: "支付宝公钥证书内容" 